name: Snap.

on:
  push:
    branches:
      - master
    paths-ignore:
      - 'docs/**'
      - '**.md'
      - 'changelog.txt'
      - 'LEGAL'
      - 'LICENSE'
      - '.github/**'
      - 'Telegram/build/**'
      - 'Telegram/Resources/uwp/**'
      - 'Telegram/Resources/winrc/**'
      - 'Telegram/SourceFiles/platform/win/**'
      - 'Telegram/SourceFiles/platform/mac/**'
      - 'Telegram/Telegram/**'
      - 'Telegram/configure.bat'
      - 'Telegram/Telegram.plist'
  pull_request:
    types: [opened, reopened]
    branches-ignore:
      - 'compare/**'
  workflow_dispatch:
    inputs:
      buildCommit:
        description: 'Commit for building. Default it latest on branch'
        required: false
        type: string
        default: ''

jobs:

  snap:
    name: Ubuntu
    runs-on: ubuntu-latest
    if: github.repository != 'cpartisans/tdesktop'

    env:
      UPLOAD_ARTIFACT: "true"
      ARTIFACT_NAME: "Snap-PTelegram"

    steps:
      - name: Clone.
        uses: actions/checkout@v4
        if: github.event.inputs.buildCommit == ''
        with:
          fetch-depth: 0
          submodules: recursive

      - name: Clone with checkout.
        uses: actions/checkout@v4
        if: github.event.inputs.buildCommit != ''
        with:
          fetch-depth: 0
          submodules: recursive
          ref: ${{ github.event.inputs.buildCommit }}

      - name: First set up.
        run: |
          sudo iptables -P FORWARD ACCEPT
          sudo snap install --classic snapcraft
          sudo usermod -aG lxd $USER
          sudo lxd init --auto
          sudo lxd waitready

          sed -i 's/$API_ID/${{ secrets.API_ID }}/g' snap/snapcraft.yaml
          sed -i 's/$API_HASH/${{ secrets.API_HASH }}/g' snap/snapcraft.yaml

      - name: Free up some disk space.
        uses: endersonmenezes/free-disk-space@4cae28d0d8e716a770938d92630f23db5184f61f
        with:
          remove_android: true
          remove_dotnet: true
          remove_haskell: true
          remove_tool_cache: true
          remove_swap: true
          remove_packages: "azure-cli google-cloud-cli microsoft-edge-stable google-chrome-stable firefox postgresql* temurin-* *llvm* mysql* dotnet-sdk-*"
          remove_packages_one_command: true
          remove_folders: "/usr/share/swift /usr/share/miniconda /usr/share/az* /usr/share/glade* /usr/local/lib/node_modules /usr/local/share/chromium /usr/local/share/powershell"

      - name: Telegram Desktop snap build.
        run: sudo -u $USER snap run snapcraft --verbosity=debug

      - name: Move and hash artifact.
        if: env.UPLOAD_ARTIFACT == 'true'
        run: |
          rm snap/snapcraft.yaml
          artifact_name=$(echo telegram-desktop_*.snap)
          echo "ARTIFACT_NAME=$artifact_name" >> $GITHUB_ENV
          mkdir artifact
          mv $artifact_name artifact/

      - uses: actions/upload-artifact@v4
        if: env.UPLOAD_ARTIFACT == 'true'
        name: Upload artifact.
        with:
          name: ${{ env.ARTIFACT_NAME }}
          path: artifact
